import { buildToolCatalog } from "../packages/core/src/tools/catalog";

const tools = new Map(
  ["US", "AU"].flatMap((jurisdiction) =>
    buildToolCatalog(
      { type: "agent", userId: "docs-only", agentLabel: "docs" },
      { jurisdiction, defaultMatterLabel: "docs", executionMode: "subscription" }
    ).map((tool) => [tool.name, tool] as const)
  )
);
const body = `---
title: MCP tools
description: Generated reference for the subscription-only GitMatter connector.
---

{/* Generated by scripts/generate-mcp-docs.ts. Edit tool definitions, then run vp run docs:tools. */}

The connector at \`/api/mcp\` uses your assistant's own reasoning. It does not launch GitMatter LLM provider calls. Hosting and external research services may have separate costs. The built-in assistant also uses this shared catalog, with additional provider-funded tools.

Read source documents, create a review (or prepare one with \`run_playbook\`), then populate findings with \`write_cell\` and exact source quotes. Document edits remain proposals until a person accepts or rejects them in GitMatter. Review cells record agent findings; they are not human approvals.

The combined catalog below contains ${tools.size} tools. Legal research availability depends on jurisdiction. After an update, refresh your client's tool catalog or reconnect if it still shows removed tools. \`run_cell\` and \`draft_playbook\` are available through the built-in assistant, not this subscription-only connector. \`resolve_document_edit\` is reserved for people in the UI.

${[...tools.values()].sort((a, b) => a.name.localeCompare(b.name)).map((tool) => `## \`${tool.name}\`

${tool.description.replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll("{", "&#123;").replaceAll("}", "&#125;")}

Inputs: ${Object.keys(tool.schema).map((key) => `\`${key}${tool.schema[key]!.isOptional() ? "?" : ""}\``).join(", ") || "none"}.

${tool.readOnly ? "Reads existing data." : "Changes workspace data; recorded under the acting account."}${tool.openWorld ? " Uses an external research service." : ""}
`).join("\n")}`;
const file = Bun.file(new URL("../docs/api-reference/mcp-tools.mdx", import.meta.url));
if (process.argv.includes("--check")) {
  if (await file.text() !== body) {
    console.error("MCP reference is out of date. Run vp run docs:tools.");
    process.exitCode = 1;
  }
} else {
  await Bun.write(file, body);
}
